### ISSUE TITLE
Installation and setup instructions

### ISSUE THREAD

**Issue by TerrySmithDC** [TerrySmithDC/tailwindcss-vertical-rhythm#8]
Update the readme to have some getting started instructions

* npm install
* tailwind configuration
* explain factor classes
* explain scale options
* show how to disable dynamic mode

**Comment by Megatank58** [comment]
#18 Updates the readme

**Comment by creater-shikha** [comment]
wana work on this..

**Comment by Megatank58** [comment]
> wana work on this..

Hello there i have opened #18 so you could give any suggestions if you have there?

**Comment by Ritika457** [comment]
Hey, @TerrySmithDC can you please assign this issue to me. I can fix this.

**Comment by Megatank58** [comment]
> Hey, @TerrySmithDC can you please assign this issue to me. I can fix this.

Hello there i have already opened the PR at #18 if you have any suggestions could you send them there

**Comment by TerrySmithDC** [comment]
Sorry @creater-shikha and @Ritika457 I missed the requests, however Megatank did open the PR first. I've all ready accepted @Megatank58 's PR however meaningful edits are still welcome!

**Comment by TerrySmithDC** [comment]
Closing this one as there is now a readme, I'll make a new readme update ticket to leave open, feel free to make PRs there if you find types, grammar issues, want to add better use cases etc.
